#pvc we have the storage we are claiming now # in pvc we have pv information
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-expense
spec:
  storageClassName: "efs-expense" # Empty string must be explicitly set otherwise default StorageClass will be set
  # volumeName: ebs-dynamic #we are not creating manually
  accessModes:
    - ReadWritemany
  resources:
    requests:
      storage: 3Gi
---
#pod get the storage through the pvc
apiVersion: v1
kind: Pod
metadata:
  name: efs-expense
  labels:
    purpose: efs-expense
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1b
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run  -v hostpath:containerpath.
    - name: efs-expense
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-expense # this will come from PVC
    persistentVolumeClaim:
      claimName: efs-expense
---
#Service 
apiVersion : v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-expense
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 #container port
    nodePort: 30007