# apiVersion : v1
# kind : Pod
# metadata :
#   name: nginx
# spec:
#   containers:
#   - name: nginx
#     image: nginx:stable-perl

apiVersion: app/v1
kind: replicas
metadata:
  name: nginx
  labels:
    tier: frontend
    app: nginx
spec: 
  selectors:
  replicas: 3
    matchlabels:
      tier: frontend
      app: nginx
    templets:
      metadata:
        tier: frontend
        app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx
---
#service
apiVersion: v1
kind: service
metadata:
  name: nginx
spec:
  selectors:
    tier: frontend
    app: nginx
  ports: 
  - name: nginx-svc-ports
    protocol: TCP
    ports: 80 # service port
    targetport: 80 # container port