apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env :
      - name: course
        valueFrom:
          configMapKeyRef:
            name: nginx-config # name of the config map you are referring to
            key : course # env.name and config map key name can be diffrent
      - name: duration
        valueFrom:
          configMapKeyRef:
            name: nginx-config
            key : "120hrs" # env .name and config map key
      - name: trainer
        valueFrom:
          configMapKeyRef:
            name: nginx-config
            key : "shiva"

          # valueFrom: , configMapKeyRef: check befor going apply naming 
        