apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    images: nginx
    env :
      - name: course
        valuefrom:
        configmapkeyref:
          name: nginx-config # name of the config map you are referring to
          key : course # env.name and config map key name can be diffrent
      - name: duration
        valuefrom:
        configmapkeyref:
          name: nginx-config
          key : "120hrs" # env .name and config map key
      # - name: trainer
      #   valuefrom:
      #   configmapkeyref:
      #     name: nginx-config
      #     key : "shiva"