apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels: # these are the replicaset lables.
    app: nginix
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector: 
  # these are used to select the pod to create replices.
  matchLabels:
      tier: frontend
      app: nginx
  # this is pod definition
  template: 
    metadata:
    # this labes belongs to pod.
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable:perls
---
apiVersion : v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    tier: frontend
    app: nginx
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 #container port




